### ISSUE TITLE
Can't push to heroku

### ISSUE THREAD

**Issue by zenspider** [seattlerb/seattlerb.org#126]
```
remote:        Running: rake assets:precompile
remote:        rake aborted!
remote:        KeyError: key not found
remote:        /tmp/build_1584f86c47dc257a8dd38555901b8fb1/config/initializers/devise.rb:22:in `fetch'
remote:        /tmp/build_1584f86c47dc257a8dd38555901b8fb1/config/initializers/devise.rb:22:in `block in <top (required)>'
remote:        /tmp/build_1584f86c47dc257a8dd38555901b8fb1/vendor/bundle/ruby/2.0.0/gems/devise-3.4.1/lib/devise.rb:293:in `setup'
remote:        /tmp/build_1584f86c47dc257a8dd38555901b8fb1/config/initializers/devise.rb:1:in `<top (required)>'
remote:        /tmp/build_1584f86c47dc257a8dd38555901b8fb1/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `load'
remote:        /tmp/build_1584f86c47dc257a8dd38555901b8fb1/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `block in load'
```

**Comment by phiggins** [comment]
I generated those keys and added them to the heroku env, and now we can push. Yay!

@tlynam has volunteered to figure out if we need all of the keys that I added.
